[package]
name = "llama-cpp-sys-3"
version = "0.5.10"
edition = "2021"
description = "llama.cpp bindings"
license = "MIT"
exclude = ["external/llama.cpp/.git", "external/llama.cpp/models/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1.54"
bindgen = "0.71.1"

[dev-dependencies]
rand = "0.9.0"

[features]
cuda = []
cuda_f16 = ["cuda"]
native = []
# TODO(mdegans): vulkan, kompute, clblast, mpi, CUDA on Windows, etc.
